#ifndef BOSDK_ERROR_CODE_H_
#define BOSDK_ERROR_CODE_H_

#ifdef __cplusplus
 extern "C" {
#endif

typedef enum{
  BOSDK_OK = 0,
  BOSDK_ERR_MEMORY = 1,
  BOSDK_ERR_FULL = 2,
  BOSDK_ERR_EMPTY = 3,
  BOSDK_ERR_NULL = 4,
  BOSDK_ERR_INVAILD_INDEX = 5,

  BOSDK_ERR_I2C_READ = 10,
  BOSDK_ERR_I2C_WRITE = 11,

  BOSDK_ERR_INVALID_CMD = 100,
  BOSDK_ERR_INVALID_LENGTH = 239,
  BOSDK_ERR_FLASH_INVALID_CHECK_SUM = 240,
  BOSDK_ERR_FLASH_INVALID_TAG = 241,
  BOSDK_ERR_INVALID_FW = 242,
  BOSDK_ERR_FLASH_ADDR_ALIGN = 243,
  BOSDK_ERR_FLASH_INVALID_ADDR = 244,
  BOSDK_ERR_FLASH_ERROR = 245,
  BOSDK_ERR_FLASH_BUSY = 246,
  BOSDK_ERR_FLASH_ERR_TIMEOUT = 247,
  BOSDK_ERR_FLASH_NOT_EMPTY = 248,
  BOSDK_ERR_FLASH_WRITE = 249,
  BOSDK_ERR_FLASH_READ = 250,
  BOSDK_ERR_FLASH_ERASE = 251,
  BOSDK_ERR_FLASH_PACKET_SIZE = 252,
  BOSDK_ERR_FLASH_SIZE = 253,
  BOSDK_ERR_FLASH_CRC = 254,

  BOSDK_ERR_MEMORY_ERASE_LENGTH = 300,
  BOSDK_ERR_MEMORY_ERASE_ALIGN = 301,
  BOSDK_ERR_MEMORY_ERASE_PARAM = 302,
  BOSDK_ERR_MEMORY_ERASE_RANGE = 304,
  BOSDK_ERR_MEMORY_READ_LENGTH = 305,
  BOSDK_ERR_MEMORY_READ_PARAM = 306,
  BOSDK_ERR_MEMORY_READ_RANGE = 307,
  BOSDK_ERR_MEMORY_WRITE_LENGTH = 308,
  BOSDK_ERR_MEMORY_WRITE_PARAM = 309,
  BOSDK_ERR_MEMORY_WRITE_ALIGN = 310,
  BOSDK_ERR_MEMORY_WRITE_RANGE = 311
} bosdk_err_t;

#ifdef __cplusplus
 }
#endif

#endif /* BOSDK_ERROR_CODE_H_ */
